[project]
name = "lumina"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mediapipe==0.10.5",
    "opencv-python>=4.12.0.88",
    "psutil>=7.1.3",
    "pyqt6>=6.10.1",
    "requests>=2.32.5",
]
